# i1 = Item(name="Water", price=50)
# i1.save()
# i2 = Item(name="IceTea", price=100)
# i2.save()
# i3 = Item(name="Ice Americano", price=120)
# i3.save()
# i4 = Item(name="Juice", price=150)
# i4.save()
# i5 = Item(name="mojito", price=200)
# i5.save()
# > p1 = Purchase(name="Edil", age="23", item=i1, date_purchase=timezone.now())
# p1.save()
# p2 = Purchase(name="Altynai", age="33", item=i3, date_purchase=timezone.now())
# p2.save()
# p3 = Purchase(name="Uluk", age="30", item=i5, date_purchase=timezone.now())
# p3.save()
# p4 = Purchase(name="Artur", age="17", item=i5, date_purchase=timezone.now())
# p4.save()
# p5 = Purchase(name="Roni", age="22", item=i4, date_purchase=timezone.now())
# p5.save()
# p6 = Purchase(name="Ermek", age="28", item=i3, date_purchase=timezone.now())
# p6.save()
# p7 = Purchase(name="Bermet", age="23", item=i4, date_purchase=timezone.now())
# p7.save()
# p8 = Purchase(name="Elzar", age="28", item=i2, date_purchase=timezone.now())
# p8.save()
# p9 = Purchase(name="Cholpon", age="30", item=i5, date_purchase=timezone.now())
# p9.save()
# p10 = Purchase(name="Nursultan", age="28", item=i1, date_purchase=timezone.now())
# p10.save()
#

